#!/bin/bash
. /var/openpanel/api/sh/module.sh

User.update() {
  userid=$(coreval User id)
  newpass=$(coreval User password)
  authd setuserpass "${userid}" "${newpass}"

  ftp_enabled=$(coreval User enable_ftp)
  [ "${ftp_enabled}" = "true" ] && authd runscript openapp-enable_ftp || authd runscript openapp-disable_ftp
}

Module.getconfig() {
  cat << _EOF_
  <openpanel.module>
    <dict id="User" type="class">
      <dict id="openpanel-admin">
	    <string id="password">*</string>
      </dict>
    </dict>
  </openpanel.module>
_EOF_
  exitquiet
}

implement OpenAppUser.module
