#!/bin/bash

## This script enables FTP on OpenApp

if [ ! -x /usr/sbin/openapp-pureftpd-auth ]; then
    /usr/bin/apt-get -q update > /dev/null
    /usr/bin/apt-get -q -y --force-yes install openpanel-openapp-pureftpd-auth > /dev/null
else
    /usr/sbin/update-rc.d pure-ftpd start 20 2 3 4 5 . stop 80 1 . >/dev/null
    /usr/sbin/invoke-rc.d pure-ftpd restart > /dev/null
fi
